#!/usr/bin/env bash
# Quick start guide for hash-based routing demos

echo "🚀 WorkflowPool Hash-Based Routing Demos"
echo "========================================"
echo ""
echo "📚 Documentation:"
echo "  - docs/hash-routing-guide.md        - Comprehensive guide"
echo "  - docs/hash-based-routing.md        - Detailed reference"
echo ""
echo "🎯 Available Demos:"
echo ""
echo "1️⃣  Basic Demo (Educational)"
echo "   Shows core concepts without real servers"
echo "   Command: bun scripts/pool-hash-routing-demo.ts [--verbose]"
echo "   Output: Scenario walkthrough with statistics"
echo ""
echo "2️⃣  Advanced Demo (Integration)"
echo "   Integration demo, works with optional real ComfyUI servers"
echo "   Command: bun scripts/pool-hash-routing-advanced.ts"
echo "   With servers: COMFY_HOSTS=host1:8188,host2:8188 bun scripts/pool-hash-routing-advanced.ts"
echo ""
echo "📖 Quick Start:"
echo ""
echo "  # Run basic demo"
echo "  bun scripts/pool-hash-routing-demo.ts"
echo ""
echo "  # Run with verbose output"
echo "  bun scripts/pool-hash-routing-demo.ts --verbose"
echo ""
echo "  # Run advanced demo"
echo "  bun scripts/pool-hash-routing-advanced.ts"
echo ""
echo "  # Run advanced demo with real servers"
echo "  COMFY_HOSTS=http://localhost:8188,http://localhost:8189 \\"
echo "  bun scripts/pool-hash-routing-advanced.ts"
echo ""
echo "✨ Key Features:"
echo "  • Deterministic workflow identification via SHA-256 hashing"
echo "  • Workflow-level failure tracking (not client-level)"
echo "  • Automatic failover to healthy clients"
echo "  • Configurable cooldown periods"
echo "  • Real-time blocking/unblocking events"
echo "  • Multi-tenant safe isolation"
echo ""
echo "🔍 Monitoring:"
echo "  Use 'client:blocked_workflow' event to detect issues"
echo "  Use 'client:unblocked_workflow' event to track recovery"
echo "  Use 'job:progress', 'job:completed', 'job:failed' for metrics"
echo ""
